# docker-compose.yml

version: '3'
services:
  web:
    image: ruby:2.7.0
    container_name: cities-app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cities_database
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: cities-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cities_database

